Scenes:
  $id: 2
  $values: []
Config: 1
OutputDirectory: "Builds"
PackagingMode: 2
AssetMode: 1
MaxPakSizeMB: 2048
ActiveProfileGuid: "216ca161-19c1-4659-a022-2bff063d3157"
ActivePipelineId: "xengine.harmonyos"
PlatformProfiles:
  $id: 3
  $values:
    - Platform: 0
      SelfContained: false
      PublishTrimmed: false
      WindowWidth: 1280
      WindowHeight: 720
      ScriptingDefineSymbols:
        $id: 5
        $values: []
      $id: 4
      $type: "XEngine.Editor.Build.DesktopBuildProfile, XEngine.Editor"
$id: 1
$type: "XEngine.Editor.Projects.Settings.BuildSettings, XEngine.Editor"
