using System;
using System.Collections.Generic;
using System.IO;
using System.Text.Json;

using XEngine.Animation;
using XEngine.Runtime;

namespace XEngine.Zonezero;

/// <summary>
/// Runtime injection of Unity FBX animation events (StartHit/StopHit, SetOutLeftFoot/RightFoot)
/// into imported <see cref="AnimationClip"/>s. The events live in the
/// <c>unity-anim-events.json</c> sidecar written at copy time; injection happens at runtime
/// because FBX sub-asset caches are regenerated by the model importer and cannot carry
/// project-side edits persistently. <see cref="XEngine.Animation.AnimationEventBinder"/> binds
/// the authored clip events to MonoBehaviour methods at play time.
/// </summary>
public static class ZonezeroAnimEvents
{
    public sealed class ClipEventEntry
    {
        public float Time { get; set; }
        public string Function { get; set; } = string.Empty;
        public float FloatParam { get; set; }
        public int IntParam { get; set; }
        public string Data { get; set; } = string.Empty;
    }

    public sealed class ClipMeta
    {
        public bool Loop { get; set; }
        public List<ClipEventEntry> Events { get; set; } = new();
    }

    /// <summary>fbx relative path (sidecar-rooted) → clip name → meta.</summary>
    private static Dictionary<string, Dictionary<string, ClipMeta>>? s_loaded;
    private static string s_loadedFrom = string.Empty;

    /// <summary>Loads (once per path) the sidecar next to or above the given anchor asset.</summary>
    public static Dictionary<string, Dictionary<string, ClipMeta>>? Load(string anchorAssetAbsolutePath)
    {
        if (s_loaded != null && s_loadedFrom == anchorAssetAbsolutePath) return s_loaded;
        DirectoryInfo? dir = new(Path.GetDirectoryName(Path.GetFullPath(anchorAssetAbsolutePath))!);
        while (dir != null)
        {
            string sidecar = Path.Combine(dir.FullName, "unity-anim-events.json");
            if (File.Exists(sidecar))
            {
                try
                {
                    s_loaded = JsonSerializer.Deserialize<Dictionary<string, Dictionary<string, ClipMeta>>>(
                        File.ReadAllText(sidecar));
                    s_loadedFrom = anchorAssetAbsolutePath;
                    return s_loaded;
                }
                catch (Exception ex)
                {
                    Runtime.Debug.LogWarning($"[Zonezero] Failed to read animation events sidecar '{sidecar}': {ex.Message}");
                    return null;
                }
            }
            dir = dir.Parent;
        }
        return null;
    }

    /// <summary>Test hook: clears the cached sidecar.</summary>
    public static void InvalidateCache()
    {
        s_loaded = null;
        s_loadedFrom = string.Empty;
    }

    /// <summary>Applies authored events (and returns the loop flag) for a clip to
    /// <paramref name="clip"/>. The FBX path is matched by tail against sidecar keys so callers
    /// can pass any absolute path of the same file.</summary>
    public static bool ApplyToClip(AnimationClip clip, string fbxAbsolutePath, string clipName)
    {
        if (clip == null || string.IsNullOrEmpty(fbxAbsolutePath)) return false;
        Dictionary<string, Dictionary<string, ClipMeta>>? map = Load(fbxAbsolutePath);
        if (map == null) return false;

        string normalized = fbxAbsolutePath.Replace('\\', '/');
        bool loop = false;
        bool matched = false;
        foreach (var kvp in map)
        {
            if (!normalized.EndsWith(kvp.Key.Replace('\\', '/'), StringComparison.OrdinalIgnoreCase)) continue;
            if (!kvp.Value.TryGetValue(clipName, out ClipMeta? meta))
            {
                if (kvp.Value.Count != 1) continue;
                foreach (ClipMeta only in kvp.Value.Values) meta = only;
            }
            if (meta == null) continue;

            matched = true;
            loop = meta.Loop;
            clip.Events.Clear();
            foreach (ClipEventEntry entry in meta.Events)
            {
                clip.Events.Add(new AnimationClipEvent
                {
                    Time = entry.Time,
                    FunctionName = entry.Function,
                    FloatParam = entry.FloatParam,
                    IntParam = entry.IntParam,
                    StringParam = entry.Data,
                });
            }
            break;
        }
        return matched ? loop : false;
    }
}
